const char* const commodity_abi = R"=====(
{
  "____comment": "This file was generated by kcwio-abigen. DO NOT EDIT - 2019-09-04T11:54:17",
  "version": "kcwio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "goodsx_info",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "uUuid",
          "type": "uint64"
        },{
          "name": "abcdAppid",
          "type": "string"
        },{
          "name": "abcdWho",
          "type": "string"
        },{
          "name": "abcdWhat",
          "type": "string"
        },{
          "name": "abcdWhen",
          "type": "string"
        },{
          "name": "abcdWhere",
          "type": "string"
        },{
          "name": "abcdContext",
          "type": "string"
        },{
          "name": "chain_time",
          "type": "uint64"
        }
      ]
    },{
      "name": "store_info",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "uUuid",
          "type": "uint64"
        },{
          "name": "abcdAppid",
          "type": "string"
        },{
          "name": "abcdWhat",
          "type": "string"
        },{
          "name": "abcdWhen",
          "type": "string"
        },{
          "name": "abcdWhere",
          "type": "string"
        },{
          "name": "abcdContext",
          "type": "string"
        },{
          "name": "chain_time",
          "type": "uint64"
        }
      ]
    },{
      "name": "scenic_info",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "uUuid",
          "type": "uint64"
        },{
          "name": "abcdAppid",
          "type": "string"
        },{
          "name": "abcdWhat",
          "type": "string"
        },{
          "name": "abcdWhen",
          "type": "string"
        },{
          "name": "abcdWhere",
          "type": "string"
        },{
          "name": "abcdContext",
          "type": "string"
        },{
          "name": "chain_time",
          "type": "uint64"
        }
      ]
    },{
      "name": "tourist_info",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "uUuid",
          "type": "uint64"
        },{
          "name": "abcdAppid",
          "type": "string"
        },{
          "name": "abcdWhat",
          "type": "string"
        },{
          "name": "abcdWhen",
          "type": "string"
        },{
          "name": "abcdWhere",
          "type": "string"
        },{
          "name": "abcdContext",
          "type": "string"
        },{
          "name": "chain_time",
          "type": "uint64"
        }
      ]
    },{
      "name": "kachuo_info",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "uUuid",
          "type": "uint64"
        },{
          "name": "abcdAppid",
          "type": "string"
        },{
          "name": "abcdWhat",
          "type": "string"
        },{
          "name": "abcdWhen",
          "type": "string"
        },{
          "name": "abcdWhere",
          "type": "string"
        },{
          "name": "abcdContext",
          "type": "string"
        },{
          "name": "chain_time",
          "type": "uint64"
        }
      ]
    },{
      "name": "saccount_info",
      "base": "",
      "fields": [{
          "name": "scenic_name",
          "type": "name"
        },{
          "name": "user_name",
          "type": "name"
        },{
          "name": "uUuid",
          "type": "uint64"
        }
      ]
    },{
      "name": "setgoodsx",
      "base": "",
      "fields": [{
          "name": "goodsName",
          "type": "name"
        },{
          "name": "abcdContext",
          "type": "string"
        },{
          "name": "abcdWhat",
          "type": "string"
        },{
          "name": "abcdAppid",
          "type": "string"
        },{
          "name": "user",
          "type": "name"
        },{
          "name": "abcdWhen",
          "type": "string"
        },{
          "name": "abcdWhere",
          "type": "string"
        }
      ]
    },{
      "name": "setstore",
      "base": "",
      "fields": [{
          "name": "userName",
          "type": "name"
        },{
          "name": "abcdAppid",
          "type": "string"
        },{
          "name": "abcdWhat",
          "type": "string"
        },{
          "name": "abcdWhen",
          "type": "string"
        },{
          "name": "abcdWhere",
          "type": "string"
        },{
          "name": "abcdContext",
          "type": "string"
        }
      ]
    },{
      "name": "setscenic",
      "base": "",
      "fields": [{
          "name": "userName",
          "type": "name"
        },{
          "name": "abcdAppid",
          "type": "string"
        },{
          "name": "abcdWhat",
          "type": "string"
        },{
          "name": "abcdWhen",
          "type": "string"
        },{
          "name": "abcdWhere",
          "type": "string"
        },{
          "name": "abcdContext",
          "type": "string"
        }
      ]
    },{
      "name": "settourist",
      "base": "",
      "fields": [{
          "name": "userName",
          "type": "name"
        },{
          "name": "abcdAppid",
          "type": "string"
        },{
          "name": "abcdWhat",
          "type": "string"
        },{
          "name": "abcdWhen",
          "type": "string"
        },{
          "name": "abcdWhere",
          "type": "string"
        },{
          "name": "abcdContext",
          "type": "string"
        }
      ]
    },{
      "name": "setkachuo",
      "base": "",
      "fields": [{
          "name": "userName",
          "type": "name"
        },{
          "name": "abcdAppid",
          "type": "string"
        },{
          "name": "abcdWhat",
          "type": "string"
        },{
          "name": "abcdWhen",
          "type": "string"
        },{
          "name": "abcdWhere",
          "type": "string"
        },{
          "name": "abcdContext",
          "type": "string"
        }
      ]
    }
  ],
  "actions": [{
      "name": "setgoodsx",
      "type": "setgoodsx",
      "ricardian_contract": ""
    },{
      "name": "setstore",
      "type": "setstore",
      "ricardian_contract": ""
    },{
      "name": "setscenic",
      "type": "setscenic",
      "ricardian_contract": ""
    },{
      "name": "settourist",
      "type": "settourist",
      "ricardian_contract": ""
    },{
      "name": "setkachuo",
      "type": "setkachuo",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "goods",
      "index_type": "i64",
      "key_names": [
        "owner"
      ],
      "key_types": [
        "name"
      ],
      "type": "goodsx_info"
    },{
      "name": "store",
      "index_type": "i64",
      "key_names": [
        "owner"
      ],
      "key_types": [
        "name"
      ],
      "type": "store_info"
    },{
      "name": "tourist",
      "index_type": "i64",
      "key_names": [
        "owner"
      ],
      "key_types": [
        "name"
      ],
      "type": "tourist_info"
    },{
      "name": "kachuo",
      "index_type": "i64",
      "key_names": [
        "owner"
      ],
      "key_types": [
        "name"
      ],
      "type": "kachuo_info"
    },{
      "name": "saccounts",
      "index_type": "i64",
      "key_names": [
        "scenic_name"
      ],
      "key_types": [
        "name"
      ],
      "type": "saccount_info"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": [],
  "variants": []
})=====";
